import Head from "next/head";
import { useQuery } from "@apollo/client";
import { GET_MEMBERS } from "@/gql/gql";
import MemberCard from "@/component/MemberCard";
import { IMemberResponse } from "@/gql/types";
import Link from "next/link";

export default function Home() {
  const { data: memberList, error } = useQuery<IMemberResponse>(GET_MEMBERS, {
    fetchPolicy: "cache-first",
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {memberList &&
          memberList.members?.map((member) => (
            <div key={member.no}>
              <MemberCard
                no={member.no}
                name={member.name}
                gender={member.gender}
                birthday={member.birthday}
                jobStartYear={member.jobStartYear}
                joinedYear={member.joinedYear}
                profileImg={member.profileImg}
                jobGrade={member.jobGrade}
                role={member.role}
              />
            </div>
          ))}
        <Link href='/register'>
          <button>등록하러가기</button>
        </Link>
      </main>
    </>
  );
}
